version: "2"
services:
    proxy:
        image: pitilezard/nginx-proxy-swarm:1.21.0.labels
        container_name: proxy
        build:
            context: .
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    whoami:
        image: jwilder/whoami
        environment:
            - VIRTUAL_HOST=whoami.local
