version: "3.8"
name: nginx-proxy

services:
    proxy:
        image: pitilezard/nginx-proxy-swarm:1.27.0.labels
        container_name: proxy
        build:
            context: .
            args:
                - NGINX_VERSION=1.27.0
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    whoami:
        image: jwilder/whoami
        labels:
            - VIRTUAL_HOST=whoami.local
