version: "3.8"
services:
    proxy:
        image: pitilezard/nginx-proxy-swarm:1.21.1.labels
        container_name: proxy
        build:
            context: .
            args:
                - NGINX_VERSION=1.21.1@sha256:3f13b4376446cf92b0cb9a5c46ba75d57c41f627c4edb8b635fa47386ea29e20
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    whoami:
        image: jwilder/whoami
        labels:
            - VIRTUAL_HOST=whoami.local
